name: flutter_earthquake_detector
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  intl: ^0.19.0
  geolocator: ^13.0.2
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  permission_handler: ^11.3.1
  flutter_map_location_marker: ^9.1.1
  shimmer: ^3.0.0
  flutter_map_compass: ^1.1.0
  json_annotation: ^4.9.0
  go_router: ^14.8.0
  flutter_map_marker_cluster: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/map/map_marker.png
    - environments/.env